# Generated by Django 4.2.7 on 2024-02-05 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
