# Generated by Django 4.2.7 on 2024-02-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_voice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voice',
        ),
    ]
