# Generated by Django 4.2.7 on 2023-11-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='profile_audios/'),
        ),
    ]
